### ISSUE TITLE
Processamento e pós-processamento

### ISSUE THREAD

**Issue by lgnsparda** [Dinamica-dos-Fluidos-CFD/Helena-Barbosa--180032836#3]
- Muitas ações de pós-processamento não estão justificadas. Qual é a justificativa para escolher vários materiais para determinar o fator de atrito?
- Algumas frases estão longas.
- A frase "Sendo assim, os resultados preliminares obtidos, para este estudo paramétrico, correspondem com a realidade física, apesar da caracterização do escoamento não ter sido adequada." tem um problema. Se a caracterização do escoamento não foi a adequada, então a simulação pode ter problemas no estabelecimento de condições de contorno. Qual é a justificativa da hipótese da caracterização do escoamento não ter sido adequada?
- Melhorar a organização do texto. Muitas coisas estão soltas no texto.

**Comment by helenabarbs** [comment]
README atualizado!

**Comment by lgnsparda** [comment]
- Completar os itens que faltam
- Inserir conclusões

**Comment by helenabarbs** [comment]
Artigo atualizado, eu disponibilizei o link no ARTIGO.md

**Comment by lgnsparda** [comment]
- Na seção de materiais e métodos, sugere-se colocar os valores de dissimetria e qualidade ortogonal em tabela.
- Quais são as conclusões finais do trabalho? Está faltando no artigo e no relatório

**Comment by lgnsparda** [comment]
- Escrever o trabalho agora em formato de relatório técnico

**Comment by helenabarbs** [comment]
Professor, 
Criei um novo arquivo chamado (2) RELATÓRIO.md e lá eu disponibilizei o link para o relatório técnico, eu fiz as mudanças que achei necessárias referentes as explicações teóricas.

**Comment by helenabarbs** [comment]
Olá professor, 

coloquei o artigo em formato latex no meu repositório, com o nome ARTIGO_LaTEX.pdf. 
(OBS: eu aprendi a linguagem recentemente e como "teste de aprendizagem" utilizei o artigo dessa disciplina, então achei bom adicionar aqui como algo extra)
